import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Head>
          <title>PNPM</title>
        </Head>
        <Header />
        {children}
      </body>
    </html>
  );
}
